[project]
name = "crypto-arbitrage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "httpx>=0.28.1",
    "numpy>=1.24.4",
    "pandas>=2.0.3",
    "python-dotenv>=1.0.1",
]
